
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/tiger/.local/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
bin /home/tiger/.local/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 7.0
CUDA SETUP: Detected CUDA version 117
/home/tiger/.local/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary /home/tiger/.local/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 7.0
CUDA SETUP: Detected CUDA version 117
/home/tiger/.local/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary /home/tiger/.local/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so...
rank 4 is in stage 4
rank 5 is in stage 5
create layer: 20|create layer: 42|create layer: 21|create layer: 43|create layer: 22|create layer: 44|create layer: 23|create layer: 45|create layer: 24|create layer: 46|create layer: 25|create layer: 47|create layer: 26|create layer: 48|create layer: 27|create layer: 49|create layer: 28|create layer: 50|create layer: 29|create layer: 51|create layer: 30|create layer: 52|create layer: 31|create layer: 53|create layer: 32|create layer: 54|create layer: 33|create layer: 55|create layer: 34|create layer: 56|create layer: 35|create layer: 57|create layer: 36|create layer: 58|create layer: 37|create layer: 59|create layer: 38|create layer: 60|create layer: 39|create layer: 61|create layer: 40|create layer: 62|create layer: 41|Stage 4 module sharded
Stage 4 kv initialized
create layer: 63|Stage 5 module sharded
Stage 5 kv initialized
rank_src: 4, rank_dst: 0, rank: 5, results_cb: Nonerank_src: 3, rank_dst: 5, rank: 4, results_cb: None

2023-05-30 12:57:35,170 - INFO - handle_cmd: stop
2023-05-30 12:57:35,200 - INFO - handle_cmd: stop
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /opt/tiger/launch/qsync/QPipe/tests/main_p2p.py:329 in <module>                                  │
│                                                                                                  │
│   326 │   │   model_pre_and_post = model_pre_and_post.cuda()                                     │
│   327 │                                                                                          │
│   328 │   run_pipeline_p2p(loaded_llm_cpu, dist_cfg, sharding_strategy=sharding_strategy)        │
│ ❱ 329 │   simple_queue_thread.join()                                                             │
│   330 │   # from torch import profiler                                                           │
│   331 │   # from torch.profiler import profile, record_function, ProfilerActivity                │
│   332 │   # with profiler.profile(activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA], wi   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'join'
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /opt/tiger/launch/qsync/QPipe/tests/main_p2p.py:329 in <module>                                  │
│                                                                                                  │
│   326 │   │   model_pre_and_post = model_pre_and_post.cuda()                                     │
│   327 │                                                                                          │
│   328 │   run_pipeline_p2p(loaded_llm_cpu, dist_cfg, sharding_strategy=sharding_strategy)        │
│ ❱ 329 │   simple_queue_thread.join()                                                             │
│   330 │   # from torch import profiler                                                           │
│   331 │   # from torch.profiler import profile, record_function, ProfilerActivity                │
│   332 │   # with profiler.profile(activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA], wi   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'join'
terminate called without an active exception
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 534864 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 534865) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main_p2p.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-05-30_12:57:36
  host      : n128-099-084.byted.org
  rank      : 5 (local_rank: 1)
  exitcode  : 1 (pid: 534865)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
